apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: kube-system
stringData:
    api-token: ENC[AES256_GCM,data:7MjdUk2GcKOIxp7FcH4V3LWM+Fve/6OUmd9/lkWAXfzW/vn1u6wugZ7f4K10fOQfEL6ucBs=,iv:61LJ+nUbNPmFoN1hDRsNptj3NJANTGTlEs5Y++LM9VQ=,tag:Q/FCxmseZrAs3G43Qo14xw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVDlRQzFSUGRjcHhHU0Zl
            NzZ5ZldpUk55eFB4NnNEcTBuL2srV2pwTWhvClJ1UkdDUDdHWUE1THJFSkMxZmdk
            N01wWWdiVktUL2kvdk90NzhJN2g1VGsKLS0tIE5HcDV1NFJJZVNyeWlQNm5lYUc5
            Y05TeVVja3Z6RlE2bWZ2ZkVPZ2pkcEkK3rDuNYBwPQ5qxytCcVYV5JEKc8ZKcNL2
            Bey7zNZP5HVTooAcWk9POWly9NfTixRMTa9Xt9xi59Z69/qT2MH6iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:38:53Z"
    mac: ENC[AES256_GCM,data:HrPA7uV/Rxt8pGWFluwTELDRxmIHFU8vobs5zn38LzfIXtiBOyttkefJffbPse6VtxvpoXNw2DXmd4ZX55XBQANKadaFhwYBf28i+wrXSkIilVw0Ktkv1U78hwtxSIHaAPD88QdKHmS/G9J6WN2LVL9p+JeRZZX4dDOQbJeeg5U=,iv:n4J6mQQQ6yI32H1uXX3TVWIbTWgykQjZlT7D3O9ujoo=,tag:kVrUwLWeS+6qiKIpw0J/nA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: default
stringData:
    DB_URL: ENC[AES256_GCM,data:5IzJARugS10uuByBBGAxdfTNBKgpasjCauZgZL7ogMtYLUJI7zCg/fwfpNoNmgWIVoagS3iFf12poMGUIsRY13gg7E12sQ/MV7I9SLD6huJAXlpl0dOZ62/5Gbam4qF4Oiu3VPKd7L98mj+nH/wciAEb6ldHoiqH1ujhOwAobQbR6Lh825lh+TDblfiUJVGxM/OfZp8=,iv:AiBQdHoUUa2Vc8l7tiusYfPY57hdPJQ7cm8yaQOC1tE=,tag:SFiHVjsDERY3tFkVYQXTGA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVDlRQzFSUGRjcHhHU0Zl
            NzZ5ZldpUk55eFB4NnNEcTBuL2srV2pwTWhvClJ1UkdDUDdHWUE1THJFSkMxZmdk
            N01wWWdiVktUL2kvdk90NzhJN2g1VGsKLS0tIE5HcDV1NFJJZVNyeWlQNm5lYUc5
            Y05TeVVja3Z6RlE2bWZ2ZkVPZ2pkcEkK3rDuNYBwPQ5qxytCcVYV5JEKc8ZKcNL2
            Bey7zNZP5HVTooAcWk9POWly9NfTixRMTa9Xt9xi59Z69/qT2MH6iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:38:53Z"
    mac: ENC[AES256_GCM,data:HrPA7uV/Rxt8pGWFluwTELDRxmIHFU8vobs5zn38LzfIXtiBOyttkefJffbPse6VtxvpoXNw2DXmd4ZX55XBQANKadaFhwYBf28i+wrXSkIilVw0Ktkv1U78hwtxSIHaAPD88QdKHmS/G9J6WN2LVL9p+JeRZZX4dDOQbJeeg5U=,iv:n4J6mQQQ6yI32H1uXX3TVWIbTWgykQjZlT7D3O9ujoo=,tag:kVrUwLWeS+6qiKIpw0J/nA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: storagebox-secret
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:cfY6dCvHey50kF5afGw+lG0LsXxAzIflMgS3+8f3DuOv/AKV+gMYq+fHpJglPaPH,iv:Y2g7uSP3AGX8meDKUl9iBWpQHti6sMk8DY57AQAI22Q=,tag:n1C0HxVmK4HwqNKRYuTkag==,type:str]
    username: ENC[AES256_GCM,data:ch7UgyeUgw==,iv:8LBHQQHZ6gAmiv7mklQsBO7BEiIVLHjuXsntGuvmcuM=,tag:RjERkC4LwaTAGoD5Pz+b9w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVDlRQzFSUGRjcHhHU0Zl
            NzZ5ZldpUk55eFB4NnNEcTBuL2srV2pwTWhvClJ1UkdDUDdHWUE1THJFSkMxZmdk
            N01wWWdiVktUL2kvdk90NzhJN2g1VGsKLS0tIE5HcDV1NFJJZVNyeWlQNm5lYUc5
            Y05TeVVja3Z6RlE2bWZ2ZkVPZ2pkcEkK3rDuNYBwPQ5qxytCcVYV5JEKc8ZKcNL2
            Bey7zNZP5HVTooAcWk9POWly9NfTixRMTa9Xt9xi59Z69/qT2MH6iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:38:53Z"
    mac: ENC[AES256_GCM,data:HrPA7uV/Rxt8pGWFluwTELDRxmIHFU8vobs5zn38LzfIXtiBOyttkefJffbPse6VtxvpoXNw2DXmd4ZX55XBQANKadaFhwYBf28i+wrXSkIilVw0Ktkv1U78hwtxSIHaAPD88QdKHmS/G9J6WN2LVL9p+JeRZZX4dDOQbJeeg5U=,iv:n4J6mQQQ6yI32H1uXX3TVWIbTWgykQjZlT7D3O9ujoo=,tag:kVrUwLWeS+6qiKIpw0J/nA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-env
    namespace: default
stringData:
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:CDiYgX4xlJpDKQb+WP1Z6g==,iv:MYFv8VJ2RFY53gIZsfL9u0fL8H5poAN7PIyWAcokoIc=,tag:bf2VRcr1Cntt/iEiNK34Aw==,type:str]
    AIOSTREAMS_AUTH_ADMINS: ENC[AES256_GCM,data:XDxi+lnz/Q==,iv:Cjo8EPtEi93YTDh+CAA5q2OJx38zDXB2T4CWyHdEuEk=,tag:cw/6avi6IPs0lAPWRvwNPg==,type:str]
    BASE_URL: ENC[AES256_GCM,data:P3waOkpMFye6+BYtWZWfCk6ZJI+R5QsWBgax+nc=,iv:hMIoUN71V/7qOhPkzY9kCLkQ7YNVce3Hx9G+3Qe4QGE=,tag:hvjQw38ljKW094voo7mk6A==,type:str]
    DATABASE_URI: ENC[AES256_GCM,data:HUm5/rLYMd6xudPATHSs613HOdFv0bEoLjayNj4=,iv:ZCTTaFmkQyF7cIRAjPdE176cQe6Ap+YyxP6MnTbPDAk=,tag:2pGdnOERN1MvvMvdJd7wng==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:M1TPWZ2afCO1giduBlWSfw2zH0Fxe54BrrhzO0zPGjO0EOdWVbvk8FZy6KLud6Kd4Bg8FKMe8bs4z5PNmHcUdQ==,iv:Biw6K3YyawZ4HKuVUYkhURtYGmDDkGGYIhMPZj1zRQc=,tag:o8PkHBP2RXwjM2v39pRPoA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVDlRQzFSUGRjcHhHU0Zl
            NzZ5ZldpUk55eFB4NnNEcTBuL2srV2pwTWhvClJ1UkdDUDdHWUE1THJFSkMxZmdk
            N01wWWdiVktUL2kvdk90NzhJN2g1VGsKLS0tIE5HcDV1NFJJZVNyeWlQNm5lYUc5
            Y05TeVVja3Z6RlE2bWZ2ZkVPZ2pkcEkK3rDuNYBwPQ5qxytCcVYV5JEKc8ZKcNL2
            Bey7zNZP5HVTooAcWk9POWly9NfTixRMTa9Xt9xi59Z69/qT2MH6iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:38:53Z"
    mac: ENC[AES256_GCM,data:HrPA7uV/Rxt8pGWFluwTELDRxmIHFU8vobs5zn38LzfIXtiBOyttkefJffbPse6VtxvpoXNw2DXmd4ZX55XBQANKadaFhwYBf28i+wrXSkIilVw0Ktkv1U78hwtxSIHaAPD88QdKHmS/G9J6WN2LVL9p+JeRZZX4dDOQbJeeg5U=,iv:n4J6mQQQ6yI32H1uXX3TVWIbTWgykQjZlT7D3O9ujoo=,tag:kVrUwLWeS+6qiKIpw0J/nA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-auth
    namespace: default
type: Opaque
data: {}
stringData:
    passwd-0: ENC[AES256_GCM,data:YoW87EfR5K/sow5hSecycBf4PwMQW5QiOlYJK0nP24T/XLLWblJJAm+OOG7Ge2WgNWojkSdTaLgGFzvBS6waqpu6ALXLdUSSd3F4/k4IgtrhIQm5iTQ7m9SBp3GznVEkueE5XXMJdTbLFzSBE1MMoxW6CGbfG/fODhm+Ovn/V/HTbuSKUboD3qXSeQSxJAopZEcpO1oPWF3q6zbB2qKqwZqkmhQrDiLS8qIDSX26Wve54uqacxaUuPCgpQMfUu6aPTgjoK/OfZ+uI99YRks/4p6iXLQ07Uz4EhcruEzdhpT9Y0efZIEjjuiSQMSkU9c3DUls1+cqa/PdkEYXbGIq2gtUAiBFhgrvsHgOR4Jij5CVW3Q5R7371/Fyai6BIgh3sodA49XIO/xR37ayEqdfw6InYMG8L0r/4+QAbeDO4dOjP1jEjzMgARdQoRS4b68qDG44GNrCIHUPUqKr/NTitC0At9NIwElQo5SC0reB87noE9LFm7cJHWUf8uj2Wr234Ovwcn4kDe1tLwhkpwUbdv+ib93ei99SFXdj5SmditD7JGQroSFTRqB+AlEU6AQ+SzNXEbKOA18=,iv:tT+v5ioN1BTprNLUYE/K9sgnGYVeXrMZJtwboZoe6ok=,tag:yUuGvx5fT0qYxqiMK/2l2A==,type:str]
    acl-0.conf: ENC[AES256_GCM,data:C0mhWEnrFPT4aWT9dHDi56rUauCJF0ohvRDvXLVgr4ZReshGZ48kht+hBBGWdRjxtgtxsKhS17nhYmzX6dOuaP7zBlNSlxpgZk2WAAyyRWHzMfxWtpybto6s+nelO7YBRQ==,iv:CZBC+kSYVvfUbPoCgO2p2yoC0NreREpIidYkii1bX90=,tag:+Qvctnvbf9jqcou6NUy6dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVDlRQzFSUGRjcHhHU0Zl
            NzZ5ZldpUk55eFB4NnNEcTBuL2srV2pwTWhvClJ1UkdDUDdHWUE1THJFSkMxZmdk
            N01wWWdiVktUL2kvdk90NzhJN2g1VGsKLS0tIE5HcDV1NFJJZVNyeWlQNm5lYUc5
            Y05TeVVja3Z6RlE2bWZ2ZkVPZ2pkcEkK3rDuNYBwPQ5qxytCcVYV5JEKc8ZKcNL2
            Bey7zNZP5HVTooAcWk9POWly9NfTixRMTa9Xt9xi59Z69/qT2MH6iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:38:53Z"
    mac: ENC[AES256_GCM,data:HrPA7uV/Rxt8pGWFluwTELDRxmIHFU8vobs5zn38LzfIXtiBOyttkefJffbPse6VtxvpoXNw2DXmd4ZX55XBQANKadaFhwYBf28i+wrXSkIilVw0Ktkv1U78hwtxSIHaAPD88QdKHmS/G9J6WN2LVL9p+JeRZZX4dDOQbJeeg5U=,iv:n4J6mQQQ6yI32H1uXX3TVWIbTWgykQjZlT7D3O9ujoo=,tag:kVrUwLWeS+6qiKIpw0J/nA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mqtt-credentials
    namespace: default
stringData:
    homebridge-password: ENC[AES256_GCM,data:nR9q0hmVNEWhohxra11byk37x6z1RTIWlOufgEV2bZA=,iv:TTmv6G/up5eYMjMKtKjGALVoIvrsDFwBjik1KmCgR58=,tag:k+oVwnIKM+4lrSWI1/nwbg==,type:str]
    z2m-password: ENC[AES256_GCM,data:C2ownxhM/oza8NhhM0t+RK6rmrzgk6zlmnSnAOP8w+U=,iv:+cugAuVZxaq9QFz04uIyaKEFVh4DiwVG1PFB28nJkWQ=,tag:aaA/NEh9RM0iSSFJI+7I9w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVDlRQzFSUGRjcHhHU0Zl
            NzZ5ZldpUk55eFB4NnNEcTBuL2srV2pwTWhvClJ1UkdDUDdHWUE1THJFSkMxZmdk
            N01wWWdiVktUL2kvdk90NzhJN2g1VGsKLS0tIE5HcDV1NFJJZVNyeWlQNm5lYUc5
            Y05TeVVja3Z6RlE2bWZ2ZkVPZ2pkcEkK3rDuNYBwPQ5qxytCcVYV5JEKc8ZKcNL2
            Bey7zNZP5HVTooAcWk9POWly9NfTixRMTa9Xt9xi59Z69/qT2MH6iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:38:53Z"
    mac: ENC[AES256_GCM,data:HrPA7uV/Rxt8pGWFluwTELDRxmIHFU8vobs5zn38LzfIXtiBOyttkefJffbPse6VtxvpoXNw2DXmd4ZX55XBQANKadaFhwYBf28i+wrXSkIilVw0Ktkv1U78hwtxSIHaAPD88QdKHmS/G9J6WN2LVL9p+JeRZZX4dDOQbJeeg5U=,iv:n4J6mQQQ6yI32H1uXX3TVWIbTWgykQjZlT7D3O9ujoo=,tag:kVrUwLWeS+6qiKIpw0J/nA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: default
stringData:
    admin-user: ENC[AES256_GCM,data:GPfusjw=,iv:BSSy/6QP94V2u8/SXgrqeInVtU+6kmjQE4xXcN3Tx3I=,tag:iThQIrojNfK+XO8SMYuKqA==,type:str]
    admin-password: ENC[AES256_GCM,data:pz8LdcehKplOQIV4/4z+PtyS3TeZVGmaLwF5Mw==,iv:UP5P5jCe8Kyv1i6UgESDJikwfLtGXhSLfipXaXeAFqE=,tag:IqpskIhdk3OwRQ6HkaF7Gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVDlRQzFSUGRjcHhHU0Zl
            NzZ5ZldpUk55eFB4NnNEcTBuL2srV2pwTWhvClJ1UkdDUDdHWUE1THJFSkMxZmdk
            N01wWWdiVktUL2kvdk90NzhJN2g1VGsKLS0tIE5HcDV1NFJJZVNyeWlQNm5lYUc5
            Y05TeVVja3Z6RlE2bWZ2ZkVPZ2pkcEkK3rDuNYBwPQ5qxytCcVYV5JEKc8ZKcNL2
            Bey7zNZP5HVTooAcWk9POWly9NfTixRMTa9Xt9xi59Z69/qT2MH6iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:38:53Z"
    mac: ENC[AES256_GCM,data:HrPA7uV/Rxt8pGWFluwTELDRxmIHFU8vobs5zn38LzfIXtiBOyttkefJffbPse6VtxvpoXNw2DXmd4ZX55XBQANKadaFhwYBf28i+wrXSkIilVw0Ktkv1U78hwtxSIHaAPD88QdKHmS/G9J6WN2LVL9p+JeRZZX4dDOQbJeeg5U=,iv:n4J6mQQQ6yI32H1uXX3TVWIbTWgykQjZlT7D3O9ujoo=,tag:kVrUwLWeS+6qiKIpw0J/nA==,type:str]
    version: 3.13.3
