apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: kube-system
stringData:
    api-token: ENC[AES256_GCM,data:96tybqUSMTtqVp/hHsWTdo2v4K457d5uIyQkpL3Y7rjJbBWuP/iGlJI6AxniBnd9Wf9Lqpg=,iv:+W0zUJjm0LP/w6gtnQQQ1+I3rxU3qtNIJ1k0nRpnZcc=,tag:v52XYLBN5LiBvOLNQ7ljWg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlJCL1ZZbXRmL0FuUzgw
            ZXkxYSs4YlJwSjNqd1VDRTM2a0R4T1pydndjCjN1azRnNlhDSHJmRmZ4RHRPaUZW
            Vmp1RzlrT0M5YUQ1Nnd6dFZEK01FeHMKLS0tIHpHMENjRHlVM2FORFZ2eHJNK29n
            c0xlSjU3QkNtMU5EK2h0a2Y3enRGODAKJw6KT2N/zxGS3JBgQmjLVvpamwNxyEaY
            kXNJbCF443iQp2uJodK60HgS/8efIaRETrw3x6im8c4fwDqAksG8HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:36:01Z"
    mac: ENC[AES256_GCM,data:KyC2iA/YN3azpt2Ou4+ki9a5pY+epFmL121+uutUF2VxJbC40xC3+AxHWsG2hPh/MBRj3f4a7Y++GeQwwV6/KATGL/u1SL1dygbZ+ByAPvEjLEK8iJ6THP00ld9QX2ZOCMNq1YyqwgLp1hToI+F3a50lWhW0fsBPoj8D8H8yTK0=,iv:QSBD2P+0KU8u8ktvWxCqfmxemhD8DM3Siiq/RTLsmOo=,tag:xuIU37zDMXQaXIl39S0YDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: default
stringData:
    DB_URL: ENC[AES256_GCM,data:m02SEyeox906bUFwQxTC8hgAoxcA1DG8mKgt6CMC7Sy+zlOFrRzDbhKHmGtqAImJ2pf0nYL3oHsIO9h78Srz6cC7bpAVPQOpY8AlG7qDwdyxt5tSo49hnrV8iRBv0fizLbuP5C9gTY4sR1gt2SF1Mm4ZdwTwiOE/nVHoNuszOLuk3QaqLc5Vt7u9xVRRg+41yf7Hp0s=,iv:/p33vwdDdj68MbSKiViLR9dT8287q6OeOL7cP/K8jnU=,tag:fFnOPov40/TKS3Ub3+enoA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlJCL1ZZbXRmL0FuUzgw
            ZXkxYSs4YlJwSjNqd1VDRTM2a0R4T1pydndjCjN1azRnNlhDSHJmRmZ4RHRPaUZW
            Vmp1RzlrT0M5YUQ1Nnd6dFZEK01FeHMKLS0tIHpHMENjRHlVM2FORFZ2eHJNK29n
            c0xlSjU3QkNtMU5EK2h0a2Y3enRGODAKJw6KT2N/zxGS3JBgQmjLVvpamwNxyEaY
            kXNJbCF443iQp2uJodK60HgS/8efIaRETrw3x6im8c4fwDqAksG8HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:36:01Z"
    mac: ENC[AES256_GCM,data:KyC2iA/YN3azpt2Ou4+ki9a5pY+epFmL121+uutUF2VxJbC40xC3+AxHWsG2hPh/MBRj3f4a7Y++GeQwwV6/KATGL/u1SL1dygbZ+ByAPvEjLEK8iJ6THP00ld9QX2ZOCMNq1YyqwgLp1hToI+F3a50lWhW0fsBPoj8D8H8yTK0=,iv:QSBD2P+0KU8u8ktvWxCqfmxemhD8DM3Siiq/RTLsmOo=,tag:xuIU37zDMXQaXIl39S0YDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: storagebox-secret
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:y6bhbRiUoxzPoKcrGmbyH5A8dI+im0kh1jnm55e+Xi1OwFaSL9jjaQKlSO53FnqF,iv:XdSsixX2EGtVdk6brpc4MPjGC+LpOAmph8fjz/r5wbE=,tag:WVqQ0ljswrpi0xahvrZ3jg==,type:str]
    username: ENC[AES256_GCM,data:0NUKsYodvA==,iv:NL9iP/tUS22E3G91YrruRwXCtSr+iETE5hK9kZOj/sc=,tag:ugwUAhlgFsbVwXS5L2msAQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlJCL1ZZbXRmL0FuUzgw
            ZXkxYSs4YlJwSjNqd1VDRTM2a0R4T1pydndjCjN1azRnNlhDSHJmRmZ4RHRPaUZW
            Vmp1RzlrT0M5YUQ1Nnd6dFZEK01FeHMKLS0tIHpHMENjRHlVM2FORFZ2eHJNK29n
            c0xlSjU3QkNtMU5EK2h0a2Y3enRGODAKJw6KT2N/zxGS3JBgQmjLVvpamwNxyEaY
            kXNJbCF443iQp2uJodK60HgS/8efIaRETrw3x6im8c4fwDqAksG8HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:36:01Z"
    mac: ENC[AES256_GCM,data:KyC2iA/YN3azpt2Ou4+ki9a5pY+epFmL121+uutUF2VxJbC40xC3+AxHWsG2hPh/MBRj3f4a7Y++GeQwwV6/KATGL/u1SL1dygbZ+ByAPvEjLEK8iJ6THP00ld9QX2ZOCMNq1YyqwgLp1hToI+F3a50lWhW0fsBPoj8D8H8yTK0=,iv:QSBD2P+0KU8u8ktvWxCqfmxemhD8DM3Siiq/RTLsmOo=,tag:xuIU37zDMXQaXIl39S0YDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-env
    namespace: default
stringData:
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:4G/L3CByv1o4jI8PRMQizQ==,iv:HrHuJyVDRVxE3RLTr7kJOjBcTGQkvXMtAmn9Stkaje4=,tag:sH4yQ7LlyWi8ZdPvS+uITA==,type:str]
    AIOSTREAMS_AUTH_ADMINS: ENC[AES256_GCM,data:yETDLUNMiw==,iv:p85K3zKzCsHAipvZibF0iFySaqziyRJt2S0WVjaRUMk=,tag:Mu+PzuZH/fvTxkwpjtt5nA==,type:str]
    BASE_URL: ENC[AES256_GCM,data:j+d8//bMr44MPjpraVnxmSEu/HY16wia+JLws38=,iv:TSsH3WZR+trCAK9GoQWofj4x5zY57/lqYmG3Pkg6CHs=,tag:tqJ3D6if3aN/dnmF4+kCtQ==,type:str]
    DATABASE_URI: ENC[AES256_GCM,data:8k57Dur7VlUKoEmrAJOqy27DkaSvdAvFgcYBfpU=,iv:JjWgr/sR5TEmU3Bq2EPLK9Duc7Uoa1ntY1wMJ5vhamc=,tag:lXxbmZtlFfPBENX2qg1N0g==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:sT0EKi2awGijrpgcVUUDIW8+GmAzhmfDHcjM0gFEpuUk0bjA83kMlM8uPYRwjGdfQ6FkSwSVcT+LaPzDo0yG/g==,iv:OcZ0vH3Hj5G+1GFXZUUGdwZuzzULb3ED0+te67Ph2fg=,tag:6JWafYajJnkfQNcLNWjmKw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlJCL1ZZbXRmL0FuUzgw
            ZXkxYSs4YlJwSjNqd1VDRTM2a0R4T1pydndjCjN1azRnNlhDSHJmRmZ4RHRPaUZW
            Vmp1RzlrT0M5YUQ1Nnd6dFZEK01FeHMKLS0tIHpHMENjRHlVM2FORFZ2eHJNK29n
            c0xlSjU3QkNtMU5EK2h0a2Y3enRGODAKJw6KT2N/zxGS3JBgQmjLVvpamwNxyEaY
            kXNJbCF443iQp2uJodK60HgS/8efIaRETrw3x6im8c4fwDqAksG8HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:36:01Z"
    mac: ENC[AES256_GCM,data:KyC2iA/YN3azpt2Ou4+ki9a5pY+epFmL121+uutUF2VxJbC40xC3+AxHWsG2hPh/MBRj3f4a7Y++GeQwwV6/KATGL/u1SL1dygbZ+ByAPvEjLEK8iJ6THP00ld9QX2ZOCMNq1YyqwgLp1hToI+F3a50lWhW0fsBPoj8D8H8yTK0=,iv:QSBD2P+0KU8u8ktvWxCqfmxemhD8DM3Siiq/RTLsmOo=,tag:xuIU37zDMXQaXIl39S0YDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-auth
    namespace: default
type: Opaque
data: {}
stringData:
    passwd-0: ENC[AES256_GCM,data:Snz9RIgC61IGErzdbnpu2n4XaA23jekvAiYk9I8ucTi2Bz9YB8kiU8cqcrwdb12bH3eR+QAj95p9fQc1TUpiXX1UUlh2zth6E04jrRnB335CzXQihzaadNM4o49CE36vcpNHa77r8ZDkf1jfe2v83/TLsJo505p4Wr9VLRdsU58xRVM4SO1+mVZFbx2l7ArlJzMleiXMHCWKUxEhaW2yubyXDF15ZEb0YCFNGgYFxqVMIl75TFGFZa9GIXR9Db9hCkyJemFMvgUiafKqmTPIVplJrBFuX0jeND3M4BDZnkgbijc5Jl/Tcx4x2hhPZrsdQGIE3TLEo8HSsT4KZ6s0lOWL2e0WpOVa1KS0jlCUqwfI7eMMfsamy1oOa3KctagnO+pO8E61gRN3ChO1DKwdOP+2gXnrrLHmKnkxkxwOCZMaLxrGM/tdJAXoHQ0MrG/ouO6mow4P4I3SfIcmeY0rUwW1jOSCtte19SUGBk/0GSSJDXHdNGEqnXVL23SdqnSFq/LwGG7thB/tBL5fkdFUjPx2bmjrMzXFjwBQYDfr7H3SMzjnmY9BmURY15ED906d8lmqX6e31l8=,iv:9OYLnvU8Ma1iTgxoilX6qHzVcUUSM0Jbc8t4y0t7+bA=,tag:A0KFql2J2Odiu5GbUkfZYQ==,type:str]
    acl-0.conf: ENC[AES256_GCM,data:lGj9Zh1AMXNsM5Ocu8IPcyBDBtKoA7ioTb3WFjwBhxEhukMya2HnbDalkEzzhFOiUwLLfnqdUOwfW4r4jw28GouQrULyg68fGFqk85CT21VaQzL1tuCroK3EfiDX/wq0xA==,iv:66SusZvM6GWrEJ8kWHkCjkNZNOab2pGheoVfGZNbvuM=,tag:g9NzwmJ1O9GSjCNuI+7nFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlJCL1ZZbXRmL0FuUzgw
            ZXkxYSs4YlJwSjNqd1VDRTM2a0R4T1pydndjCjN1azRnNlhDSHJmRmZ4RHRPaUZW
            Vmp1RzlrT0M5YUQ1Nnd6dFZEK01FeHMKLS0tIHpHMENjRHlVM2FORFZ2eHJNK29n
            c0xlSjU3QkNtMU5EK2h0a2Y3enRGODAKJw6KT2N/zxGS3JBgQmjLVvpamwNxyEaY
            kXNJbCF443iQp2uJodK60HgS/8efIaRETrw3x6im8c4fwDqAksG8HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:36:01Z"
    mac: ENC[AES256_GCM,data:KyC2iA/YN3azpt2Ou4+ki9a5pY+epFmL121+uutUF2VxJbC40xC3+AxHWsG2hPh/MBRj3f4a7Y++GeQwwV6/KATGL/u1SL1dygbZ+ByAPvEjLEK8iJ6THP00ld9QX2ZOCMNq1YyqwgLp1hToI+F3a50lWhW0fsBPoj8D8H8yTK0=,iv:QSBD2P+0KU8u8ktvWxCqfmxemhD8DM3Siiq/RTLsmOo=,tag:xuIU37zDMXQaXIl39S0YDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mqtt-credentials
    namespace: default
stringData:
    homebridge-password: ENC[AES256_GCM,data:EJhKhrk9OOpVLTvw33fy4gt7+3TGu8oby3Mq7ofWxpc=,iv:Y8aniIrfd4wtT4WvcVGL8T2i81W3sVRfXcPyvIH/gQ4=,tag:uqw0bjP2FWs6wK2W4utU9g==,type:str]
    z2m-password: ENC[AES256_GCM,data:ulQjFXFBbz9umBVsnTyXhu9cuPkeLW+zFLYFwy2HuQ8=,iv:uhbRWirUCBQlV/t+pWoydWp+chCUoeN7JGbwiWh006A=,tag:QFB3EE7Qw0ApGW2ZYyZMUg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlJCL1ZZbXRmL0FuUzgw
            ZXkxYSs4YlJwSjNqd1VDRTM2a0R4T1pydndjCjN1azRnNlhDSHJmRmZ4RHRPaUZW
            Vmp1RzlrT0M5YUQ1Nnd6dFZEK01FeHMKLS0tIHpHMENjRHlVM2FORFZ2eHJNK29n
            c0xlSjU3QkNtMU5EK2h0a2Y3enRGODAKJw6KT2N/zxGS3JBgQmjLVvpamwNxyEaY
            kXNJbCF443iQp2uJodK60HgS/8efIaRETrw3x6im8c4fwDqAksG8HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:36:01Z"
    mac: ENC[AES256_GCM,data:KyC2iA/YN3azpt2Ou4+ki9a5pY+epFmL121+uutUF2VxJbC40xC3+AxHWsG2hPh/MBRj3f4a7Y++GeQwwV6/KATGL/u1SL1dygbZ+ByAPvEjLEK8iJ6THP00ld9QX2ZOCMNq1YyqwgLp1hToI+F3a50lWhW0fsBPoj8D8H8yTK0=,iv:QSBD2P+0KU8u8ktvWxCqfmxemhD8DM3Siiq/RTLsmOo=,tag:xuIU37zDMXQaXIl39S0YDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: openobserve-root
    namespace: default
type: Opaque
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:4XOfkELDAfDSuK/yUCNo5Q==,iv:da2UKLRvMy6JHM+I/FnBj5Lvc1209zanMMX6wXLEDFM=,tag:7d4SWwMGTe2L/Dq84O9vUw==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:qpdcIFmGUdkZXcXZnGAv8e00/1mFsPbpmu6tnCw=,iv:omBMHvDkRUazsJAICWLrYCbd4gB9mDQ00RkcU/Xw5FM=,tag:MGHFzmSlQCcSHviHwL/aCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlJCL1ZZbXRmL0FuUzgw
            ZXkxYSs4YlJwSjNqd1VDRTM2a0R4T1pydndjCjN1azRnNlhDSHJmRmZ4RHRPaUZW
            Vmp1RzlrT0M5YUQ1Nnd6dFZEK01FeHMKLS0tIHpHMENjRHlVM2FORFZ2eHJNK29n
            c0xlSjU3QkNtMU5EK2h0a2Y3enRGODAKJw6KT2N/zxGS3JBgQmjLVvpamwNxyEaY
            kXNJbCF443iQp2uJodK60HgS/8efIaRETrw3x6im8c4fwDqAksG8HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:36:01Z"
    mac: ENC[AES256_GCM,data:KyC2iA/YN3azpt2Ou4+ki9a5pY+epFmL121+uutUF2VxJbC40xC3+AxHWsG2hPh/MBRj3f4a7Y++GeQwwV6/KATGL/u1SL1dygbZ+ByAPvEjLEK8iJ6THP00ld9QX2ZOCMNq1YyqwgLp1hToI+F3a50lWhW0fsBPoj8D8H8yTK0=,iv:QSBD2P+0KU8u8ktvWxCqfmxemhD8DM3Siiq/RTLsmOo=,tag:xuIU37zDMXQaXIl39S0YDw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: openobserve-collector-auth
    namespace: kube-system
type: Opaque
stringData:
    O2_AUTH: ENC[AES256_GCM,data:ibH1Cu22YMPuTZlvqM4SRHyneAOdy3snWDchNjr/VjHmhh/fI+AOQVJPTO8GDzwzVdgguZID1b0c9igbMNAesMX/canBKg==,iv:br14DgJZjlguEP0Ri0ZvfI38SiaOvxNXgkZ2SCXevHg=,tag:l97bw1WiQqpABJP4CvsBGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlJCL1ZZbXRmL0FuUzgw
            ZXkxYSs4YlJwSjNqd1VDRTM2a0R4T1pydndjCjN1azRnNlhDSHJmRmZ4RHRPaUZW
            Vmp1RzlrT0M5YUQ1Nnd6dFZEK01FeHMKLS0tIHpHMENjRHlVM2FORFZ2eHJNK29n
            c0xlSjU3QkNtMU5EK2h0a2Y3enRGODAKJw6KT2N/zxGS3JBgQmjLVvpamwNxyEaY
            kXNJbCF443iQp2uJodK60HgS/8efIaRETrw3x6im8c4fwDqAksG8HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:36:01Z"
    mac: ENC[AES256_GCM,data:KyC2iA/YN3azpt2Ou4+ki9a5pY+epFmL121+uutUF2VxJbC40xC3+AxHWsG2hPh/MBRj3f4a7Y++GeQwwV6/KATGL/u1SL1dygbZ+ByAPvEjLEK8iJ6THP00ld9QX2ZOCMNq1YyqwgLp1hToI+F3a50lWhW0fsBPoj8D8H8yTK0=,iv:QSBD2P+0KU8u8ktvWxCqfmxemhD8DM3Siiq/RTLsmOo=,tag:xuIU37zDMXQaXIl39S0YDw==,type:str]
    version: 3.13.3
