apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: kube-system
stringData:
    api-token: ENC[AES256_GCM,data:5iVU6LBT8nJa5yUZ6LYM7srDyVrfYtwNdWPk7mjuUf/p+Ncw87XeHFCeTHVrPZxwyyZ/k7I=,iv:29YGMob2zYEL13b7Z5WDup9ppFDQ34XKl4A8KOcQZ4M=,tag:L6XOWZ3ktwlKDH53ogznag==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcVBRaVdhL1FFUThOVlNa
            amJRUGFROFBFYTBwVy9mN1VmNldvemNqc2c0CkhWNXgrWUZTY0ppSjd5OHI3YnNR
            ZXR6YUhhMUFLMjJoNk8xY1JjUm5Pb28KLS0tIGpxOGFkS3I3WmFDRkhLQXJNblgw
            ZXo5RHRNd1Bvd0RjMWpncFNNcjliMVkKMl+Omu4A/0/p/eWsbCXsoOxOrSgjEYWP
            jcqSIpU5S6YDhmYuGkOVuXJpWhC7p2tNFBR6BX9c+d0K/OGFDxRU6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T12:25:27Z"
    mac: ENC[AES256_GCM,data:nnrex3DV5rXV9rpj0o40O5PnwUIgxck5e9gcFXRYlYnO7PenwTo8hSE6OpRzubw4g9/3ahlni8j8z8YJe3PbOAfv1Re92Wuy2XLzAjbphg2HAHkfcert5habBw82Bd9+sRTNQlSImSF/7hLGnF2Pc5/L/a1n6CaMB6p8U5NxtC4=,iv:Nlz/PjcN54wtbPKHiQanfKXKdHgIG7DL9gg27YoCKTo=,tag:l6ZfJ5YocGecAchwhO5XkA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: default
stringData:
    DB_URL: ENC[AES256_GCM,data:y4EavKd2rxvKyuaacKgIx+ZtzdY0bK1xvVNv9RSimzIaX3ph8oTMt4jx46s/n9PR4MclY2/kjUPAIxEwQ4BUq0APGd1Rb9pMuKct9L5o3vG3xG1vPqsZbrbvJpWHZUhbyzoJA/nZJsOzeLMfHogf3Pvhax0RoAEmTvtMyYDb3ZWaFwhk3b9ypczyG6Jrjs77yv24ECo=,iv:YOaZpUBQzGHTZHli4fUuBLQm0ruIatgDImv0B++hv1o=,tag:7hHdvz98WLKnUqYMcfdmXA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcVBRaVdhL1FFUThOVlNa
            amJRUGFROFBFYTBwVy9mN1VmNldvemNqc2c0CkhWNXgrWUZTY0ppSjd5OHI3YnNR
            ZXR6YUhhMUFLMjJoNk8xY1JjUm5Pb28KLS0tIGpxOGFkS3I3WmFDRkhLQXJNblgw
            ZXo5RHRNd1Bvd0RjMWpncFNNcjliMVkKMl+Omu4A/0/p/eWsbCXsoOxOrSgjEYWP
            jcqSIpU5S6YDhmYuGkOVuXJpWhC7p2tNFBR6BX9c+d0K/OGFDxRU6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T12:25:27Z"
    mac: ENC[AES256_GCM,data:nnrex3DV5rXV9rpj0o40O5PnwUIgxck5e9gcFXRYlYnO7PenwTo8hSE6OpRzubw4g9/3ahlni8j8z8YJe3PbOAfv1Re92Wuy2XLzAjbphg2HAHkfcert5habBw82Bd9+sRTNQlSImSF/7hLGnF2Pc5/L/a1n6CaMB6p8U5NxtC4=,iv:Nlz/PjcN54wtbPKHiQanfKXKdHgIG7DL9gg27YoCKTo=,tag:l6ZfJ5YocGecAchwhO5XkA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: storagebox-secret
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:ZMANt8tkwIvnXXxD+j99D78vtVrLngzTA9PEF/E9CIaZhMWOlm824wqA7Yl73Q+r,iv:ymZhHxSYwBRoRAMwRPB+EhN1HwSDihZh8FBYRoZo/0M=,tag:DEA/fh57lSjwcYM0VQacYw==,type:str]
    username: ENC[AES256_GCM,data:o8lEzmJnUQ==,iv:K8lmtwUawzDi2+giaEDqB1pTXzdvcw5zMRX2/Cqm8X8=,tag:lv2/hz9CUkWw8C8gbBsk3g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcVBRaVdhL1FFUThOVlNa
            amJRUGFROFBFYTBwVy9mN1VmNldvemNqc2c0CkhWNXgrWUZTY0ppSjd5OHI3YnNR
            ZXR6YUhhMUFLMjJoNk8xY1JjUm5Pb28KLS0tIGpxOGFkS3I3WmFDRkhLQXJNblgw
            ZXo5RHRNd1Bvd0RjMWpncFNNcjliMVkKMl+Omu4A/0/p/eWsbCXsoOxOrSgjEYWP
            jcqSIpU5S6YDhmYuGkOVuXJpWhC7p2tNFBR6BX9c+d0K/OGFDxRU6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T12:25:27Z"
    mac: ENC[AES256_GCM,data:nnrex3DV5rXV9rpj0o40O5PnwUIgxck5e9gcFXRYlYnO7PenwTo8hSE6OpRzubw4g9/3ahlni8j8z8YJe3PbOAfv1Re92Wuy2XLzAjbphg2HAHkfcert5habBw82Bd9+sRTNQlSImSF/7hLGnF2Pc5/L/a1n6CaMB6p8U5NxtC4=,iv:Nlz/PjcN54wtbPKHiQanfKXKdHgIG7DL9gg27YoCKTo=,tag:l6ZfJ5YocGecAchwhO5XkA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-env
    namespace: default
stringData:
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:v63jaBkqnLOC/EzV/HVtRg==,iv:awci2gjemJjK9IQ+JJ279cfML6EcUQez0e5CI9HeXkY=,tag:8t9piM/g5EL7fimcGI/RiQ==,type:str]
    AIOSTREAMS_AUTH_ADMINS: ENC[AES256_GCM,data:DePJTQIdfA==,iv:grqxG7XBuP51dA+sDV64aVTUrIQnJcJ9J95c6k/xYVg=,tag:H3H8YxAJF0av4KPiFQDl3A==,type:str]
    BASE_URL: ENC[AES256_GCM,data:2CnX4YgCTGU3DSZH3Z9mzR0rgJMtE7HGbo6xte8=,iv:ssihch+ywIP5PFub3yvnPKE2RjsGRG661j1eY69EDNU=,tag:IMTAcmewYB6GxaX7Ryp+EA==,type:str]
    DATABASE_URI: ENC[AES256_GCM,data:QtSX3MtbrqAN08kj3+oLyWc9Mm6/M6L9SK1l2ZU=,iv:6FGkL4gRMoM9Vi54DBAMoDz7WprfYVkUbIdXU1Q3OiE=,tag:ccIUo96XfjiLnSHkSgHrdQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:ZhSqSfThhPHXV8IPFF62J5SoiYYGHZRz45ASNwyzt8iRJpk9D4bJ9RHF4Y+yJPej0agJGBEesN5r3gzlfk/p0Q==,iv:i672s2+9he+VChnj5Sz7R66+nsGeecW35MScg9iiw9g=,tag:3lrCW9VeTFfUhxCXpzZnow==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcVBRaVdhL1FFUThOVlNa
            amJRUGFROFBFYTBwVy9mN1VmNldvemNqc2c0CkhWNXgrWUZTY0ppSjd5OHI3YnNR
            ZXR6YUhhMUFLMjJoNk8xY1JjUm5Pb28KLS0tIGpxOGFkS3I3WmFDRkhLQXJNblgw
            ZXo5RHRNd1Bvd0RjMWpncFNNcjliMVkKMl+Omu4A/0/p/eWsbCXsoOxOrSgjEYWP
            jcqSIpU5S6YDhmYuGkOVuXJpWhC7p2tNFBR6BX9c+d0K/OGFDxRU6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T12:25:27Z"
    mac: ENC[AES256_GCM,data:nnrex3DV5rXV9rpj0o40O5PnwUIgxck5e9gcFXRYlYnO7PenwTo8hSE6OpRzubw4g9/3ahlni8j8z8YJe3PbOAfv1Re92Wuy2XLzAjbphg2HAHkfcert5habBw82Bd9+sRTNQlSImSF/7hLGnF2Pc5/L/a1n6CaMB6p8U5NxtC4=,iv:Nlz/PjcN54wtbPKHiQanfKXKdHgIG7DL9gg27YoCKTo=,tag:l6ZfJ5YocGecAchwhO5XkA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-auth
    namespace: default
type: Opaque
data: {}
stringData:
    passwd-0: ENC[AES256_GCM,data:h8iQLBFQ7M1bXtVONfHiNnBKYtnd/KRrxWGkERn1+kOLKuhp1Rgj2CzAwZweqxGTkat40pjZpkHBGCd5kCt7Q0nWNY9n255WJ+N0J6Uba3lw0aNJB+tewb1PAgxaIJQnbCN3EwO/dU5AnCrgTQaJO5tqALLv7GHGETt3qlgMxR1fiiz0vjFsut8dfvr7TPSEeCHYg3GBdERRbAcOexDwi/J6WRw5aUBKcPQjbzvLz4NDNhAR/aTpfPxDYj+tFNQlMiev7Y6N1zP+lXiRQkBdF03MlClxbKNKx9jzimD9XYogLJYKmhQtCSKvZ36K6hdodEvf/30zdKP9m2dZlNievsp+nuJOM9Oq1ez7xtZ3+VnFHpZhLc8Qjx20jSAzMR1XLTR2g/6zjE3U1bDL6gbvMiLEjXUzGxGzdws2zQC/Mt3uRnWy1s3eqIfeKjHPzdujp4+EBNhC4nvw3j1zsda1A8qEvdRAm6H35DQk9SEHvw5Vdbj24gQV0zDPPVEo08jXcFf9QM7lkAGN3dkuLlEBNumaX1DCRZp3kDU6a9SH2hDssrP8hkkkLIHxCsDA/Q2JRRkTzjXiRbM=,iv:jUa6nqDrhb1AunEhV0NXbI6VAiiy5GUKT++T7v7kioI=,tag:imQzyynvsa6BJs1Y3u8oDw==,type:str]
    acl-0.conf: ENC[AES256_GCM,data:KrvkjgHcrmwKo0qC/GdfoxBM6hAICPgXL206bLwU1CrnCbc3KEV5Vac9TlfEaKTozjkzKJS8tMvYz/YyURybk1VyTMqY3LXWDD/8KdC/GwvGGk0hF3dfSTCYeglg3RfRZw==,iv:b/1+eUUH4aDyuUiDrwBYmKBtKQN4d5ICdzniuuQGYTs=,tag:1N22PQMj2JpoCEuGhkMD+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcVBRaVdhL1FFUThOVlNa
            amJRUGFROFBFYTBwVy9mN1VmNldvemNqc2c0CkhWNXgrWUZTY0ppSjd5OHI3YnNR
            ZXR6YUhhMUFLMjJoNk8xY1JjUm5Pb28KLS0tIGpxOGFkS3I3WmFDRkhLQXJNblgw
            ZXo5RHRNd1Bvd0RjMWpncFNNcjliMVkKMl+Omu4A/0/p/eWsbCXsoOxOrSgjEYWP
            jcqSIpU5S6YDhmYuGkOVuXJpWhC7p2tNFBR6BX9c+d0K/OGFDxRU6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T12:25:27Z"
    mac: ENC[AES256_GCM,data:nnrex3DV5rXV9rpj0o40O5PnwUIgxck5e9gcFXRYlYnO7PenwTo8hSE6OpRzubw4g9/3ahlni8j8z8YJe3PbOAfv1Re92Wuy2XLzAjbphg2HAHkfcert5habBw82Bd9+sRTNQlSImSF/7hLGnF2Pc5/L/a1n6CaMB6p8U5NxtC4=,iv:Nlz/PjcN54wtbPKHiQanfKXKdHgIG7DL9gg27YoCKTo=,tag:l6ZfJ5YocGecAchwhO5XkA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mqtt-credentials
    namespace: default
stringData:
    homebridge-password: ENC[AES256_GCM,data:KgP+E4cd+Ihy4rM2057BwaG0FLxD1kKtC0nUxfWtK1M=,iv:9b1sao2BfmZ5PY5zwygBwUuycrxqhKjT3VCbIxLCVAI=,tag:57gcc3l7v90CsgeVgm7X3w==,type:str]
    z2m-password: ENC[AES256_GCM,data:M6j+MrwaCU6wa4sVN0TPdS05ZnHkIdPZe4vs7gF3ogI=,iv:TKJNJAyZUFTLhKy81X5LbgfNEa0U6unr3Xh0Ubkf2YM=,tag:kyG6T4kJfDUc+5jbf02Frg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcVBRaVdhL1FFUThOVlNa
            amJRUGFROFBFYTBwVy9mN1VmNldvemNqc2c0CkhWNXgrWUZTY0ppSjd5OHI3YnNR
            ZXR6YUhhMUFLMjJoNk8xY1JjUm5Pb28KLS0tIGpxOGFkS3I3WmFDRkhLQXJNblgw
            ZXo5RHRNd1Bvd0RjMWpncFNNcjliMVkKMl+Omu4A/0/p/eWsbCXsoOxOrSgjEYWP
            jcqSIpU5S6YDhmYuGkOVuXJpWhC7p2tNFBR6BX9c+d0K/OGFDxRU6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age180pastcqgvvq49uwq086qsdg7ez2ujp7uqs7my9dpptu8p2n7vrskf9frh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T12:25:27Z"
    mac: ENC[AES256_GCM,data:nnrex3DV5rXV9rpj0o40O5PnwUIgxck5e9gcFXRYlYnO7PenwTo8hSE6OpRzubw4g9/3ahlni8j8z8YJe3PbOAfv1Re92Wuy2XLzAjbphg2HAHkfcert5habBw82Bd9+sRTNQlSImSF/7hLGnF2Pc5/L/a1n6CaMB6p8U5NxtC4=,iv:Nlz/PjcN54wtbPKHiQanfKXKdHgIG7DL9gg27YoCKTo=,tag:l6ZfJ5YocGecAchwhO5XkA==,type:str]
    version: 3.13.3
